name: ez-drl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy<2.0.0
  - pytorch
  - pip:
    - stable-baselines3[extra]>=2.0.0
    - gymnasium>=0.29.0
    - matplotlib
    - tensorboard
    - box2d-py
    - mujoco>=3.0.0
    - imageio
    - opencv-python
    - ale-py>=0.8.0
    - gymnasium[atari]
    - autorom[accept-rom-license]
